
default:
  tags:
    - gitlab-runner-shell

cache:
  paths:
    - vendor/

stages:
  - analysis
  - test

pre-job:
  stage: .pre
  script:
    - docker -v
    - docker-compose -v
    - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
    - docker-compose -f docker-compose.test.yml up -d --force-recreate --build
    - docker-compose -f docker-compose.test.yml exec -T backend composer install
    - docker-compose -f docker-compose.test.yml exec -T backend php -f /var/www/html/wait-db.php

cs:
  stage: analysis
  script:
    - docker-compose -f docker-compose.test.yml exec -T backend composer run-script cs

lint:
  stage: analysis
  script:
    - docker-compose -f docker-compose.test.yml exec -T backend composer run-script lint

test unit:
  stage: test
  script:
    - docker-compose -f docker-compose.test.yml exec -T backend php -d memory_limit=-1 vendor/bin/phpunit --colors=always --coverage-text --bootstrap tests/Unit/bootstrap.php tests/Unit/
  coverage: '/\s+Lines:\s{2,}(\d+[,.]\d+%)/'

test server:
  stage: test
  script:
    - docker-compose -f docker-compose.test.yml exec -T backend composer run-script test-server

test system:
  stage: test
  script:
    - docker-compose -f docker-compose.test.yml exec -T backend composer run-script test-system

post-job:
  stage: .post
  when: always
  script:
    - docker-compose down
