version: '3.7'

services:

  db:
    image: mysql:5.7
    container_name: mdk-db
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    networks:
      - mdk-network

  backend:
    build:
      context: ./.docker/php/
    container_name: mdk-backend
    extra_hosts:
      - "host.docker.internal:172.16.1.1"
    depends_on: 
      - db
    volumes:
      - ./coverage-report-html/:/var/www/html/coverage-report-html/
      - ./logs/:/var/log/php/
      - ./src/:/var/www/html/src/
      - ./tests/:/var/www/html/tests/
      - ./composer.json:/var/www/html/composer.json
      - ./phpstan.neon:/var/www/html/phpstan.neon
      - ./phpunit.xml:/var/www/html/phpunit.xml
      - ./wait-db.php:/var/www/html/wait-db.php
    command: /bin/bash -c "id && composer install && php -f wait-db.php && while true; do sleep 2; done;"
    networks:
      - mdk-network

networks:
  mdk-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.1/24
